### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by anchovy** [sjelfull/craft3-templateselect#11]
Hi, Is this plugin going to be upgraded to support Craft V4? Any timeline for this?
Thanks in advance.

**Comment by breizhwave** [comment]
OK I have started work on a Craft4 fork
https://github.com/breizhwave/craft4-templateselect
but I get this error
  [craft\composer\InvalidPluginException]                                               
  Couldn't install breizhwave/craft4-templateselect: Unable to determine the base path

any help welcome

**Comment by breizhwave** [comment]
works now here 
install on dev mode https://github.com/breizhwave/craft4-templateselect

**Comment by anchovy** [comment]
@sjelfull / have you got a timeframe for this being rolled out?

**Comment by chadcrowell** [comment]
Went ahead and produced a [Craft 4 compatible version](https://github.com/helloswish/template-selector) of this. Should be up on the Plugin Store any day.

**Comment by sjelfull** [comment]
@anchovy No timeframe, but happy to take PRs.

**Comment by sjelfull** [comment]
3.0.0 is out now with support for Craft 4.
