### ISSUE TITLE
Any plan to update plugin for craft 5?

### ISSUE THREAD

**Issue by miro94** [sjelfull/craft3-templateselect#15]
Do you have any plan to adjust the plugin, so it's compatible with the new craft 5 version?

**Comment by furioursus** [comment]
@miro94 i just migrated without issue to [Template Selector](https://github.com/helloswish/template-selector). It works just fine *and* includes a “pretty print” feature for your template names.

**Comment by sjelfull** [comment]
v5.0.0 is out now with support for Craft 5, along with the UI improvements in the fork from Swish Digital + some template efficiency additions.
