### ISSUE TITLE
Template path issue on Windows with Laravel Valet

### ISSUE THREAD

**Issue by ipetrov87** [sjelfull/craft3-templateselect#3]
I am trying to use the extension for one of the project that I just start to work. The idea is to put template select field in a matrix field and select a template for each matrix component. So here is the configuration of the matrix field:

![matrix field configuration](https://user-images.githubusercontent.com/14108063/41168280-2ce1ab66-6b4e-11e8-82bb-e6518d346e25.png)

First I notice that I get the absolute path in the field when I am in the entry instead just the stripped filenames:

![used in entry](https://user-images.githubusercontent.com/14108063/41168550-ff5c781e-6b4e-11e8-9d13-07f5a0045bd8.png)

I was think that this is some strange bug that will not affect me when I used it in the template. But I was wrong. When i try to open the page in the browser i get this:

![loading the template](https://user-images.githubusercontent.com/14108063/41168684-6136a406-6b4f-11e8-8ca6-84c7dad8f139.png)

So I am on Windows 10 and using [vitr/valet4windows](https://github.com/vitr/valet4windows)

**Comment by sjelfull** [comment]
Problem is I don't use Windows and doesn't have access to a Windows machine to test this either. I'm open to Pull requests, though.

**Comment by ipetrov87** [comment]
I think i found what is the problem. Since I am on Windows my path separator should be **\** not **/**. When I change it all is working like a charm. It will be annoying to change all when I move the project to production..... If you have some idea on how to fix this

**Comment by ipetrov87** [comment]
It is all about the **DIRECTORY_SEPARATOR**. In Windows it returns **\** and my path was entered with **/**. So that`s why I see the entire path and not just the file name. It will be annoying to change all my paths every time when I move it on Linux server.

**Comment by okolvik-avento** [comment]
Made a patch for it at #7 
Works on both windows and linux
