### ISSUE TITLE
Use a separate template path.

### ISSUE THREAD

**Issue by ipetrov87** [sjelfull/craft3-templateselect#4]
My idea is to make one matrix field with several components that can be used on many places. For that reason I want to have all my template, that are able to select, in one separated folder called **components**. In that folder I want to have sub-folders that contains all possible template for each component. Something like this:

![project structure](https://user-images.githubusercontent.com/14108063/41189198-9b7a4f72-6bd2-11e8-931a-385ffd8c9818.PNG)

So I add the template select field and set the sub-folder to **component/textAndImage/**. So when I go to my Homepage and select a template **imageOnLeft.twig** save it, and then I try to load the page I get this error:

**Unable to find the template “imageOnLeft.twig” in "homepage/_entry" at line 5.**

So instead to include **component/textAndImage/imageOnLeft** it just include **imageOnLeft.twig**.

Is it possible somehow to include the **Limit to subfolder** + **Selected template** instead just **Selected template**?

**Comment by sjelfull** [comment]
This is now available with v5.0.0.

These are the different options now:

### Output the chosen template name:

```twig
{{ entry.fieldHandle }}
```

### Include/Embed the chosen template:

```twig
{% include entry.fieldHandle %}
```

### Include the template including subfolder if set:

```twig
{% include entry.fieldHandle.withSubfolder() %}
```

This is a alias for the following:

```twig
{{ entry.templateWithSubfolder.template(true) }}
```

### Output the subfolder name:

```twig
{{ entry.fieldHandle.subfolder() }}
```

### Output the filename without path:

```twig
{{ entry.fieldHandle.filename() }}
```
