### ISSUE TITLE
Minimum Requirement Issue upgrading to CraftCMS 3.1

### ISSUE THREAD

**Issue by richhayler** [sjelfull/craft3-templateselect#6]
composer.json has the following:

`"require": {
  "craftcms/cms": "~3.0.0-beta.23"
},`

Needs to be updated too....

`"require": {
  "craftcms/cms": "^3.0.0-beta.23"
},`

**Comment by khalwat** [comment]
See here for the details:

https://github.com/craftcms/cms/issues/3645#issuecomment-455367876

TL;DR is that it is already fixed, the repo just needs to be tagged with a new release.
